### PR TITLE
added CMakeLists, FileOpenDialog

### PR DESCRIPTION
**Pull request by miromx**

### CODE REVIEW

**Comment by miromx** [comment]
I deleted some harcode from ui and add FileDialog for more functionality. Also, I created CMakeLists.txt for OpenCV v4

**Comment by jonilaitinen** [comment]
Thanks for the OpenCV update! Could you add the commit hash of the OpenCV version you used to test this, either to the readme or with a submodule reference to https://github.com/opencv/opencv ?

**Comment by miromx** [comment]
> Thanks for the OpenCV update! Could you add the commit hash of the OpenCV version you used to test this, either to the readme or with a submodule reference to https://github.com/opencv/opencv ?

Yep, I use OpenCV 4.6.0 , Ubuntu 20. A little bit later, I will update your README, if you like.
Your project is very cool! How about to add some functionality? i.e. after color dominant is found (#f5002e), you may return a "human readable" color (≈ Torch Red) 
Like this: https://imagecolorpicker.com/color-code/f5002e

**Comment by jonilaitinen** [comment]
Thanks! Yes that looks like a nice feature, you can create PRs fo new features if you like and I'm happy to merge them in.

**Pull request closed without merging**
